import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    justifyContent: "center",
    paddingHorizontal: 20,
    paddingVertical: 40,
    backgroundColor: "#f9fafb",
  },
  bannerContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fef2f2",
    borderColor: "#fca5a5",
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    marginBottom: 20,
  },
  bannerText: {
    flex: 1,
    fontSize: 11,
    color: "#b91c1c",
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontWeight: "600",
  },
  bannerCloseBtn: {
    padding: 2,
    marginLeft: 4,
  },
  authCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.08)",
    padding: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  cardHeader: {
    alignItems: "center",
    marginBottom: 24,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#111827",
    marginTop: 12,
  },
  headerSubtitle: {
    fontSize: 12,
    color: "#6b7280",
    textAlign: "center",
    marginTop: 6,
    lineHeight: 16,
  },
  formContainer: {
    width: "100%",
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f3f4f6",
    borderRadius: 10,
    paddingHorizontal: 12,
    height: 48,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.03)",
  },
  inputIcon: {
    marginRight: 10,
  },
  input: {
    flex: 1,
    fontSize: 14,
    color: "#111827",
    height: "100%",
  },
  rightBtn: {
    padding: 8,
  },
  forgotBtn: {
    alignSelf: "flex-end",
    marginBottom: 18,
  },
  forgotText: {
    fontSize: 12,
    color: "#2563eb",
    fontWeight: "500",
  },
  primaryBtn: {
    backgroundColor: "#dc2626",
    borderRadius: 10,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  disabledBtn: {
    backgroundColor: "#fca5a5",
  },
  primaryBtnText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "bold",
  },
  divider: {
    height: 1,
    backgroundColor: "#e5e7eb",
    marginVertical: 20,
  },
  secondaryBtn: {
    backgroundColor: "#ffffff",
    borderColor: "#e5e7eb",
    borderWidth: 1,
    borderRadius: 10,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryBtnText: {
    color: "#374151",
    fontSize: 14,
    fontWeight: "600",
  },
  backLink: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 18,
  },
  backLinkText: {
    color: "#4b5563",
    fontSize: 13,
    fontWeight: "600",
  },
  lockoutBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff5f5",
    borderColor: "#feb2b2",
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    marginBottom: 16,
  },
  lockoutText: {
    fontSize: 12,
    color: "#c53030",
    fontWeight: "600",
    flex: 1,
  },
  strengthMeterContainer: {
    marginBottom: 16,
    backgroundColor: "#f9fafb",
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  strengthTextRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  strengthTextLabel: {
    fontSize: 11,
    color: "#4b5563",
  },
  strengthValueLabel: {
    fontSize: 11,
    fontWeight: "bold",
  },
  strengthProgressBarOuter: {
    height: 6,
    backgroundColor: "#e5e7eb",
    borderRadius: 3,
    marginBottom: 12,
    overflow: "hidden",
  },
  strengthProgressBarInner: {
    height: "100%",
    borderRadius: 3,
  },
  checklistContainer: {
    gap: 6,
  },
  reqRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  reqDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  reqDotMet: {
    backgroundColor: "#22c55e",
  },
  reqDotUnmet: {
    backgroundColor: "#9ca3af",
  },
  reqText: {
    fontSize: 11,
  },
  reqTextMet: {
    color: "#166534",
  },
  reqTextUnmet: {
    color: "#6b7280",
  },
  instructionCard: {
    backgroundColor: "#eff6ff",
    borderColor: "#bfdbfe",
    borderWidth: 1,
    borderRadius: 10,
    padding: 12,
    alignItems: "center",
    marginBottom: 16,
  },
  instructionText: {
    fontSize: 12,
    color: "#1e3a8a",
    textAlign: "center",
    lineHeight: 16,
  },
  textHighlight: {
    fontWeight: "bold",
    color: "#2563eb",
  },
  resendBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    marginTop: 8,
  },
  resendBtnText: {
    color: "#2563eb",
    fontSize: 12,
    fontWeight: "600",
  },
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 99999,
    paddingHorizontal: 24,
  },
  alertCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 24,
    alignItems: "center",
    width: "100%",
    maxWidth: 320,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 10,
  },
  alertTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#111827",
    marginBottom: 8,
  },
  alertDesc: {
    fontSize: 12,
    color: "#4b5563",
    textAlign: "center",
    lineHeight: 16,
    marginBottom: 16,
  },
  alertTimer: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#dc2626",
    marginBottom: 20,
  },
  renewBtn: {
    backgroundColor: "#2563eb",
    borderRadius: 10,
    height: 44,
    paddingHorizontal: 20,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },
  renewBtnText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "bold",
  },
});

export const settingsStyles = StyleSheet.create({
  container: {
    flexDirection: "column",
    gap: 16,
    paddingVertical: 8,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#6b7280",
    letterSpacing: 1,
    marginTop: 8,
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.08)",
    padding: 16,
  },
  cardHeader: {
    fontSize: 13,
    fontWeight: "bold",
    color: "#111827",
    marginBottom: 12,
  },
  cardHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  cardDescription: {
    fontSize: 11,
    color: "#6b7280",
    lineHeight: 15,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
  },
  label: {
    fontSize: 12,
    color: "#4b5563",
  },
  value: {
    fontSize: 12,
    color: "#111827",
    fontWeight: "500",
  },
  toggleBtn: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
  },
  toggleBtnActive: {
    backgroundColor: "#e0f2fe",
    borderColor: "#7dd3fc",
  },
  toggleBtnInactive: {
    backgroundColor: "#f3f4f6",
    borderColor: "#e5e7eb",
  },
  toggleBtnText: {
    fontSize: 10,
    fontWeight: "bold",
    color: "#0369a1",
  },
  mfaSetupBox: {
    marginTop: 12,
    backgroundColor: "#f9fafb",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 8,
    padding: 12,
  },
  mfaSetupTitle: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#111827",
    marginBottom: 6,
  },
  mfaSetupSteps: {
    fontSize: 11,
    color: "#4b5563",
    lineHeight: 15,
    marginBottom: 8,
  },
  secretHighlight: {
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontWeight: "bold",
    color: "#b91c1c",
    backgroundColor: "#f3f4f6",
    paddingHorizontal: 4,
    borderRadius: 2,
  },
  qrSimulator: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    padding: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 8,
    marginVertical: 10,
    alignSelf: "center",
  },
  qrMockDotGrid: {
    width: 60,
    height: 60,
    borderWidth: 1.5,
    borderColor: "#000",
    borderRadius: 4,
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 6,
  },
  qrMockCorner: {
    width: 10,
    height: 10,
    backgroundColor: "#000",
    position: "absolute",
  },
  qrSimulatorText: {
    fontSize: 9,
    color: "#9ca3af",
    fontWeight: "600",
  },
  mfaInput: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 6,
    height: 38,
    paddingHorizontal: 10,
    fontSize: 13,
    marginBottom: 10,
  },
  mfaActionRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
  },
  mfaCancelBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: "#f3f4f6",
  },
  mfaCancelText: {
    fontSize: 11,
    color: "#4b5563",
    fontWeight: "600",
  },
  mfaConfirmBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: "#10b981",
  },
  mfaConfirmText: {
    fontSize: 11,
    color: "#ffffff",
    fontWeight: "600",
  },
  refreshBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 12,
    paddingVertical: 8,
    backgroundColor: "#eff6ff",
    borderColor: "#bfdbfe",
    borderWidth: 1,
    borderRadius: 6,
  },
  refreshBtnText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#2563eb",
  },
  logoutBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#dc2626",
    borderRadius: 8,
    height: 40,
    marginTop: 8,
  },
  logoutBtnText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "bold",
  },
});