import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  topStatusBar: {
    backgroundColor: "#ffffff",
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 0 : 12,
    paddingBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.06)",
  },
  topStatusClock: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#000000",
  },
  topStatusRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  topStatusBleText: {
    fontSize: 10,
    color: "#2563eb",
    fontWeight: "600",
    marginLeft: 4,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
  },
  header: {
    backgroundColor: "#ffffff",
    paddingHorizontal: 20,
    paddingBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.06)",
  },
  headerLeft: {
    flexDirection: "column",
  },
  headerLogoBox: {
    width: 20,
    height: 20,
    backgroundColor: "#dc2626",
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  headerTitle: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#000000",
    letterSpacing: -0.3,
  },
  headerBadge: {
    backgroundColor: "#dc2626",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    marginLeft: 8,
  },
  headerBadgeText: {
    fontSize: 9,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    color: "#ffffff",
    fontWeight: "bold",
    letterSpacing: 0.5,
  },
  headerSubtitle: {
    fontSize: 10,
    color: "#9ca3af",
    marginLeft: 6,
  },
  headerHelpBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ef4444",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 18,
    gap: 6,
  },
  headerHelpText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "bold",
  },

  sectionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#111827",
    marginBottom: 12,
  },
  logActionCard: {
    backgroundColor: "#ffffff",
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.08)",
  },
  disasterButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  disasterBtn: {
    flex: 1,
    paddingVertical: 10,
    backgroundColor: "#f3f4f6",
    borderRadius: 8,
    marginHorizontal: 4,
    alignItems: "center",
  },
  disasterBtnActive: {
    backgroundColor: "#dc2626",
  },
  disasterBtnText: {
    color: "#4b5563",
    fontSize: 12,
    fontWeight: "600",
  },
  disasterBtnTextActive: {
    color: "#ffffff",
  },
  input: {
    backgroundColor: "#f9fafb",
    color: "#1f2937",
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.08)",
    fontSize: 16,
    marginBottom: 12,
  },
  submitLogBtn: {
    backgroundColor: "#dc2626",
    padding: 14,
    borderRadius: 8,
    alignItems: "center",
  },
  submitLogBtnText: {
    color: "#ffffff",
    fontWeight: "bold",
    fontSize: 16,
  },
  headerSettingsBtn: {
    width: 36,
    height: 36,
    backgroundColor: "#f3f4f6",
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  criticalAlertBanner: {
    backgroundColor: "#dc2626",
    paddingHorizontal: 20,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  criticalAlertText: {
    fontSize: 11,
    color: "#ffffff",
    fontWeight: "600",
  },
  scrollContent: {
    flex: 1,
  },
  scrollContentContainer: {
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  bottomNav: {
    backgroundColor: "#ffffff",
    borderTopWidth: 1,
    borderTopColor: "rgba(0,0,0,0.08)",
    paddingHorizontal: 8,
    paddingTop: 8,
    flexDirection: "row",
  },
  bottomNavTab: {
    flex: 1,
    alignItems: "center",
    gap: 4,
    paddingVertical: 8,
    borderRadius: 12,
  },
  bottomNavTabActive: {
    backgroundColor: "#fef2f2",
  },
  bottomNavText: {
    fontSize: 10,
    fontWeight: "600",
  },
  // Shared Components styles extracted
  // Radar View styles
  viewContainer: {
    flexDirection: "column",
    gap: 16,
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.08)",
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  cardSubtitle: {
    fontSize: 10,
    fontWeight: "600",
    color: "#9ca3af",
    letterSpacing: 1,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#000000",
    marginTop: 2,
  },
  badge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 9999,
  },
  badgeText: {
    fontSize: 11,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontWeight: "bold",
  },
  radarWrapper: {
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 12,
  },
  radarCircle: {
    width: 208,
    height: 208,
    borderRadius: 104,
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
  },
  radarCenterDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#dc2626",
    position: "absolute",
    zIndex: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 3,
  },
  compassLabelContainer: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 5,
  },
  compassLabelText: {
    fontSize: 10,
    fontWeight: "bold",
    textAlign: "center",
  },
  arrowWrapper: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  arrowContainer: {
    height: 80,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  radarDot: {
    position: "absolute",
    zIndex: 15,
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 20,
    marginTop: 16,
  },
  statCell: {
    flex: 1,
    alignItems: "center",
  },
  statVal: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#000000",
  },
  statLabel: {
    fontSize: 10,
    color: "#9ca3af",
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    marginTop: 2,
  },
  statDivider: {
    width: 1,
    height: 28,
    backgroundColor: "rgba(0,0,0,0.1)",
  },
  listContainer: {
    flexDirection: "column",
    gap: 8,
  },
  victimCard: {
    width: "100%",
    backgroundColor: "#ffffff",
    borderRadius: 12,
    borderWidth: 1,
    padding: 16,
    flexDirection: "column",
  },
  victimCardNormal: {
    borderColor: "rgba(0,0,0,0.08)",
  },
  victimCardSelected: {
    borderColor: "#dc2626",
    shadowColor: "#dc2626",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 2,
  },
  victimCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  victimCardLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  victimCardMeta: {
    flexDirection: "column",
  },
  victimCardTitle: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#000000",
  },
  victimCardSubRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 2,
  },
  victimCardSubText: {
    fontSize: 11,
    color: "#9ca3af",
  },
  bullet: {
    color: "#e5e7eb",
    marginHorizontal: 8,
  },
  victimCardRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  heartRateContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  heartRateText: {
    fontSize: 11,
    color: "#000000",
  },
  miniBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 9999,
  },
  miniBadgeText: {
    fontSize: 10,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontWeight: "bold",
  },
  victimDetails: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(0,0,0,0.06)",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  detailCol: {
    flex: 1,
  },
  detailLabel: {
    fontSize: 9,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    color: "#9ca3af",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  detailVal: {
    fontSize: 14,
    fontWeight: "bold",
    marginTop: 4,
  },
  detailUnit: {
    fontSize: 10,
    color: "#9ca3af",
    fontWeight: "normal",
  },
  // Map View styles
  mapCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.08)",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  mapHeader: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.06)",
  },
  mapHeaderText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#000000",
    marginLeft: 8,
  },
  mapDotIndicator: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#22c55e",
    marginRight: 6,
  },
  mapHeaderStatusText: {
    fontSize: 10,
    color: "#6b7280",
  },
  mapBody: {
    backgroundColor: "#f9fafb",
    height: 280,
    position: "relative",
  },
  userIconContainer: {
    position: "absolute",
    width: 24,
    height: 24,
    marginLeft: -12,
    marginTop: -12,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
  },
  userIconWrapper: {
    position: "relative",
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  userIconPing: {
    position: "absolute",
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "rgba(37, 99, 235, 0.2)",
  },
  userIconPulse: {
    position: "absolute",
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: "rgba(37, 99, 235, 0.4)",
  },
  userIconCenter: {
    position: "absolute",
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#2563eb",
    alignItems: "center",
    justifyContent: "center",
  },
  mapCompassHud: {
    position: "absolute",
    top: 12,
    right: 16,
    backgroundColor: "#ffffff",
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.1)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
    elevation: 2,
  },
  mapCompassText: {
    fontSize: 10,
    fontWeight: "bold",
    color: "#dc2626",
  },
  mapScaleHud: {
    position: "absolute",
    bottom: 12,
    right: 16,
    alignItems: "flex-end",
    gap: 4,
  },
  mapScaleBar: {
    height: 2,
    width: 48,
    backgroundColor: "rgba(0,0,0,0.4)",
  },
  mapScaleText: {
    fontSize: 9,
    color: "rgba(0,0,0,0.4)",
  },
  legendContainer: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: "rgba(0,0,0,0.06)",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
    backgroundColor: "#ffffff",
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  legendDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  legendText: {
    fontSize: 10,
    color: "#6b7280",
  },
  navPanel: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.08)",
    padding: 16,
    flexDirection: "column",
    gap: 12,
  },
  navPanelHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  navStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 8,
  },
  navVictimLabel: {
    fontSize: 13,
    fontWeight: "bold",
    color: "#000000",
  },
  navVictimFloor: {
    fontSize: 10,
    color: "#9ca3af",
    marginLeft: 8,
  },
  navStatusText: {
    fontSize: 10,
    color: "#9ca3af",
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    marginTop: 4,
  },
  navDistanceText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#dc2626",
  },
  navBearingText: {
    fontSize: 10,
    color: "#9ca3af",
    marginTop: 2,
  },
  navActionRow: {
    flexDirection: "row",
    gap: 8,
  },
  navBtnPrimary: {
    flex: 1,
    height: 40,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  navBtnActive: {
    backgroundColor: "#f59e0b",
  },
  navBtnInactive: {
    backgroundColor: "#dc2626",
  },
  navBtnText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#ffffff",
  },
  navBtnSwitch: {
    flex: 1,
    height: 40,
    borderRadius: 10,
    backgroundColor: "#f3f4f6",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  navBtnSwitchText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#374151",
  },
  navBtnReset: {
    paddingHorizontal: 12,
    height: 40,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  navBtnResetText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#6b7280",
  },
  floorCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.08)",
    padding: 16,
  },
  floorCardTitle: {
    fontSize: 10,
    color: "#9ca3af",
    letterSpacing: 1,
    marginBottom: 12,
  },
  floorBtnRow: {
    flexDirection: "row",
    gap: 8,
  },
  floorBtn: {
    flex: 1,
    height: 36,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  floorBtnNormal: {
    backgroundColor: "#f3f4f6",
  },
  floorBtnSelected: {
    backgroundColor: "#dc2626",
  },
  floorBtnText: {
    fontSize: 12,
    fontWeight: "bold",
  },
  disabledBtn: {
    opacity: 0.5,
  },
  // Pods View styles
  podsOverviewGrid: {
    flexDirection: "row",
    gap: 12,
  },
  podsOverviewCard: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.08)",
    paddingVertical: 12,
    alignItems: "center",
  },
  podsOverviewVal: {
    fontSize: 24,
    fontWeight: "bold",
  },
  podsOverviewLabel: {
    fontSize: 9,
    color: "#9ca3af",
    letterSpacing: 0.5,
    marginTop: 4,
  },
  podCard: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.08)",
    padding: 16,
    flexDirection: "column",
  },
  podCardOffline: {
    opacity: 0.6,
  },
  podCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  podCardLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  podCardMeta: {
    flexDirection: "column",
  },
  podCardTitle: {
    fontSize: 13,
    fontWeight: "bold",
    color: "#000000",
  },
  podCardSubText: {
    fontSize: 10,
    color: "#9ca3af",
    marginTop: 2,
  },
  podStatsRow: {
    flexDirection: "row",
    gap: 12,
  },
  podStatCol: {
    flex: 1,
  },
  podStatLabel: {
    fontSize: 9,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    color: "#9ca3af",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  progressBarBg: {
    height: 6,
    backgroundColor: "#f3f4f6",
    borderRadius: 3,
    overflow: "hidden",
    marginBottom: 4,
  },
  progressBarFill: {
    height: "100%",
    borderRadius: 3,
  },
  podStatVal: {
    fontSize: 11,
    fontWeight: "600",
  },
  hopsVal: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#000000",
  },
  podAlertBanner: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fef2f2",
    borderColor: "#fecaca",
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 8,
  },
  podAlertText: {
    fontSize: 11,
    color: "#dc2626",
  },
  // Log View styles
  logCard: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.08)",
    padding: 16,
    flexDirection: "column",
  },
  logCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  logCardLabel: {
    fontSize: 10,
    fontWeight: "bold",
  },
  logCardTime: {
    fontSize: 10,
    color: "#9ca3af",
  },
  logCardMessage: {
    fontSize: 12,
    color: "rgba(0,0,0,0.8)",
    lineHeight: 18,
  },
  // Toast notifications styles
  toastOverlay: {
    position: "absolute",
    top: Platform.OS === 'ios' ? 60 : 40,
    left: 20,
    right: 20,
    zIndex: 9999,
    alignItems: "center",
  },
  toastAlert: {
    width: "100%",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
    borderWidth: 1,
  },
  toastSuccess: {
    backgroundColor: "#f0fdf4",
    borderColor: "#bbf7d0",
  },
  toastInfo: {
    backgroundColor: "#eff6ff",
    borderColor: "#bfdbfe",
  },
  toastTitle: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#1f2937",
  },
  toastDesc: {
    fontSize: 11,
    color: "#4b5563",
    marginTop: 4,
    lineHeight: 15,
  },
  // Helper utility styles
  textRed: {
    color: "#dc2626",
  },
  textRedBold: {
    color: "#dc2626",
    fontWeight: "bold",
  },
  textBlack: {
    color: "#000000",
  },
  textBlackBold: {
    color: "#000000",
    fontWeight: "bold",
  },
  textWhite: {
    color: "#ffffff",
  },
  textMuted: {
    color: "#9ca3af",
  },
  alignRight: {
    alignItems: "flex-end",
  },
  // Victim marker positions on Map
  mapVictimContainer: {
    position: 'absolute',
    width: 40,
    height: 30,
    alignItems: 'center',
    justifyContent: 'flex-start',
    transform: [{ translateX: -20 }, { translateY: -30 }],
  },
  mapVictimDot: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 3,
  },
  mapVictimText: {
    fontSize: 9,
    fontWeight: 'bold',
    color: '#ffffff',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  mapVictimStem: {
    width: 1.5,
    height: 8,
  },
  navBtnUpdate: {
    paddingHorizontal: 12,
    height: 40,
    borderRadius: 10,
    backgroundColor: "#eff6ff",
    borderWidth: 1,
    borderColor: "#bfdbfe",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  navBtnUpdateText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#2563eb",
  },
  modalOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10000,
    paddingHorizontal: 24,
  },
  modalContent: {
    width: "100%",
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 8,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#111827",
    marginBottom: 8,
  },
  modalSubtitle: {
    fontSize: 13,
    color: "#6b7280",
    marginBottom: 20,
  },
  modalOptionRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    marginBottom: 8,
    borderWidth: 1,
  },
  modalOptionDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 10,
  },
  modalOptionText: {
    fontSize: 14,
    fontWeight: "600",
  },
  modalCancelBtn: {
    marginTop: 12,
    alignItems: "center",
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: "#f3f4f6",
  },
  modalCancelBtnText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#4b5563",
  },
  // Rescuer SOS Styles
  mapSosHud: {
    position: "absolute",
    top: 12,
    left: 16,
    backgroundColor: "#ef4444",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 18,
    gap: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    borderWidth: 1.5,
    borderColor: "#ffffff",
  },
  mapSosHudText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "bold",
  },
  // Emergency user icon status colors
  userIconPingTrapped: {
    position: "absolute",
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "rgba(220, 38, 38, 0.3)",
  },
  userIconPulseTrapped: {
    position: "absolute",
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "rgba(220, 38, 38, 0.5)",
  },
  userIconCenterTrapped: {
    position: "absolute",
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#dc2626",
    alignItems: "center",
    justifyContent: "center",
  },
  userIconPingInjured: {
    position: "absolute",
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "rgba(217, 119, 6, 0.3)",
  },
  userIconPulseInjured: {
    position: "absolute",
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "rgba(217, 119, 6, 0.5)",
  },
  userIconCenterInjured: {
    position: "absolute",
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#d97706",
    alignItems: "center",
    justifyContent: "center",
  },
  // Emergency banner
  emergencyBanner: {
    backgroundColor: "#dc2626",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    paddingHorizontal: 16,
    gap: 8,
  },
  emergencyBannerText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "bold",
    letterSpacing: 0.5,
  },
});
