services:
  - type: web
    name: zamboalert-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_SECURE
        value: "false"
      - key: SMTP_USER
        value: your-gmail-address@gmail.com
      - key: SMTP_PASS
        value: your-16-character-app-password
      - key: SMTP_FROM
        value: your-gmail-address@gmail.com
