import React from "react";
import { View, Text, TouchableOpacity, ActivityIndicator } from "react-native";
import { Smartphone, ShieldCheck, ArrowLeft } from "lucide-react-native";
import { styles } from "../Auth.styles";
import { InputField } from "../../components/FormElements";

export interface MfaVerifyScreenProps {
  mfaCode: string;
  setMfaCode: (text: string) => void;
  handleVerifyMfa: () => void;
  onNavigateToLogin: () => void;
  loading?: boolean;
}

export function MfaVerifyScreen({
  mfaCode,
  setMfaCode,
  handleVerifyMfa,
  onNavigateToLogin,
  loading = false,
}: MfaVerifyScreenProps) {
  return (
    <View style={styles.formContainer}>
      <View style={styles.instructionCard}>
        <Smartphone size={20} color="#10b981" style={{ marginBottom: 8 }} />
        <Text style={styles.instructionText}>
          Multi-Factor Authentication (MFA) Active. Please enter the 6-digit token generated by your rescuer device or authenticator.
        </Text>
      </View>

      <InputField
        icon={ShieldCheck}
        placeholder="Enter 6-digit MFA Token"
        value={mfaCode}
        onChangeText={setMfaCode}
        keyboardType="numeric"
        maxLength={6}
      />

      <TouchableOpacity
        onPress={handleVerifyMfa}
        style={styles.primaryBtn}
        disabled={loading || mfaCode.length !== 6}
      >
        {loading ? (
          <ActivityIndicator color="#ffffff" size="small" />
        ) : (
          <Text style={styles.primaryBtnText}>Verify and Login</Text>
        )}
      </TouchableOpacity>

      <TouchableOpacity
        onPress={onNavigateToLogin}
        style={styles.backLink}
      >
        <ArrowLeft size={14} color="#4b5563" style={{ marginRight: 6 }} />
        <Text style={styles.backLinkText}>Cancel Authentication</Text>
      </TouchableOpacity>
    </View>
  );
}
